title: Introduction to Data Science I & II
author: the University of Chicago
copyright: "2022"
logo: "textbook/images/uchicago_python.png"  # path to a logo file

sphinx:
  config:
    execution_show_tb: true

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
    - html_image
