title: Introduction to Data Science
author: the University of Chicago
copyright: "2022"
logo: "images/logo/favicon-32x32.png"  # path to a logo file

sphinx:
  config:
    execution_show_tb: true

execute:
  timeout: 100

html:
  favicon: "images/logo/favicon.ico"  # A path to a favicon image

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
    - html_image
