name: Image

on:
  push:
    branches:
      - 'master'
    paths:
      - 'image/**'

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install management dependencies
        run: |
          pip install argcmdr==0.13.1

      # Currently only supports jupyter-service image

      - name: Build image
        run: manage --show image jupyter-service build

      - name: Push image to container registry
        run: manage --show image jupyter-service push
